version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - ./imports/realm-export.json:/opt/keycloak/data/import/realm-export.json